#!/bin/zsh
set -eu

CONSOLE_USER="$(stat -f%Su /dev/console)"
MODEL_SOURCE="/Library/Application Support/EnglishReader/Kokoro"

if [[ "$CONSOLE_USER" != "root" && "$CONSOLE_USER" != "loginwindow" && -d "$MODEL_SOURCE" ]]; then
    USER_HOME="$(dscl . -read "/Users/$CONSOLE_USER" NFSHomeDirectory | awk '{print $2}')"
    USER_MODEL_DIRECTORY="$USER_HOME/Library/Application Support/EnglishReader/Kokoro"
    mkdir -p "$USER_MODEL_DIRECTORY"
    ditto "$MODEL_SOURCE" "$USER_MODEL_DIRECTORY"
    chown -R "$CONSOLE_USER":staff "$USER_MODEL_DIRECTORY"
fi

exit 0
